const products = [
    {
        id: 0,
        name: 'Plucky McStrumface',
        amount: 0, 
        price: 16, 
        rating: 3, 
        category: 'plast 🧴',
        discountPrice: null,    
        img: {
            url: 'https://github.com/Medieinstitutet/fed24d-js-intro-inl-1-webshop-LcNyaker/blob/main/assets/product-images/product-pluckymcstrumface.png',
            widht: 1024,
            height: 1024, 
            alt: 'Ett orange transparent gitarrplektrum tillverkat i plast, med texten "Plucky McStrumFace" överst och "Plucky Guitar Pick" under en stiliserad glad smiley-ikon i mitten.',
        },
    },
    {
        id: 1,
        name: 'Pickachu',
        amount: 0, 
        price: 35, 
        rating: 5, 
        category: 'trä 🪵',    
        img: {
            url: 'assets/product-images/product-pickachu.jpg',
            widht: 1024,
            height: 1024, 
            alt: 'Ett träplektrum med ett hål nära toppen. På plektrum finns en illustration av en gul seriefigur med röda kinder och svarta örontips, omgiven av texten "Pikachu" och andra mindre markeringar.', 
        },
    },
    {
        id: 2,
        name: 'Plectrickery',
        amount: 0, 
        price: 38, 
        rating: 2, 
        category: 'metall 🔩',    
        img: {
            url: 'assets/product-images/product-plectrickery.png',
            widht: 1024,
            height: 1024, 
            alt: 'Ett metalliskt gitarrplektrum med texten "Plectrickery" ingraverad i toppen, omgiven av geometriska mönster och linjer för ett elegant och modernt utseende.',
        },
    },
    {
        id: 3,
        name: 'Shred Zeppelin',
        amount: 0, 
        price: 42, 
        rating: 3, 
        category: 'metall 🔩',    
        img: {
            url: 'assets/product-images/product-shredzeppelin.jpg',
            widht: 1024,
            height: 1024, 
            alt: 'En närbild av ett plektrum med unik design. Plektrumets bas är i silver, och dess mitt är fyllt med en struktur av sammanflätade gyllene trådar',
        },
    },
    {
        id: 4,
        name: 'Sir Strums-a-Lot',
        amount: 0, 
        price: 26, 
        rating: 2, 
        category: 'trä 🪵',    
        img: {
            url: 'assets/product-images/product-sirstrumsalot.jpg',
            widht: 1024,
            height: 1024,
            alt: 'Ett ljust träplektrum med en detaljerad gravyr på framsidan. Gravyren visar en illustration av en man som bär en hög hatt omgiven av dekorativa linjer. Texten ovanför och under illustrationen lyder: ”SIR STRUMS-A-LOT"',
        },
    },
    {
        id: 5,
        name: 'Pickle Ricktum',
        amount: 0, 
        price: 35, 
        rating: 5, 
        category: 'trä 🪵',    
        img: {
            url: 'assets/product-images/product-picklericktum.jpg',
            widht: 1024,
            height: 1024,
            alt: 'Ett plektrum av trä med tecknad design som föreställer ett grönt ansikte med ett förvånat uttryck, inspirerat av en saltgurka. Texten "Pickle" är skriven längst upp i en lekfull stil. Plektret har en ljus träfinish med ett litet hål i botten', 
        },
    },
    {
        id: 6,
        name: 'Strumb & Dumb',
        amount: 0, 
        price: 18, 
        rating: 4, 
        category: 'plast 🧴',    
        img: {
            url: 'assets/product-images/product-strumbanddumb.jpg',
            widht: 1024,
            height: 1024, 
            alt: 'Ett orange plektrum med en svartvit illustration av en person som spelar mandolin. Plektrumet har texten "STRUM" med stora bokstäver och slogans samt dekorativa texter runt kanten.',
        },
    },
    {
        id: 7,
        name: 'Pickasso',
        amount: 0, 
        price: 26, 
        rating: 2, 
        category: 'trä 🪵',    
        img: {
            url: 'assets/product-images/product-pickasso.jpg',
            widht: 1024,
            height: 1024, 
            alt: 'Ett träplektrum med en unik, färgstark geometrisk design i rött, blått, gult och grönt. Designen påminner om en stiliserad ansiktsmask med symmetriska mönster och hämtar inspiration från den store konstnären Pablo Picassos verk.',
        },
    },
    {
        id: 8,
        name: 'Pluck Norris',
        amount: 0, 
        price: 20, 
        rating: 5, 
        category: 'plast 🧴',    
        img: {
            url: 'assets/product-images/product-plucknorris.jpg',
            widht: 1024,
            height: 1024, 
            alt: 'Ett vitt plektrum med en detaljerad svartvit illustration av en man med cowboyhatt och skägg, som gör ett kraftfullt och ikoniskt intryck. Inspirationen bygger på den välkände profilen Chuck Norris.',
        },
    },
    {
        id: 9,
        name: 'Strumdog Millionaire',
        amount: 0, 
        price: 34, 
        rating: 1, 
        category: 'metall 🔩',    
        img: {
            url: 'assets/product-images/product-strumdogmillionaire.jpg',
            widht: 1024,
            height: 1024, 
            alt: 'Ett blått plektrum med en upphöjd, detaljerad gulddekor som inkluderar en utsmyckad ram och texten "STRUMDOG MILLIONAIRE". Plektrumet har en lyxig och elegant design som ger intryck av exklusivitet',
        },
    }
];

export default products;