const products = [
    {
        id: 0,
        name: 'Plucky McStrumface',
        amount: 0, 
        price: 16, 
        rating: 3, 
        category: 'plast 🧴',
        discountPrice: null,    
        img: {
            url: 'assets/product-images/Product-PluckyMcStrumface.png',
            widht: 1024,
            height: 1024, 
            alt: 'An orange transparent guitar plectrum made in plastic, with the text "Plucky McStrumFace" at the top and "Plucky Guitar Pick" below a stylized happy smiley icon in the middle.',
        },
    },
    {
        id: 1,
        name: 'Pickachu',
        amount: 0, 
        price: 35, 
        rating: 5, 
        category: 'trä 🪵',    
        img: {
            url: 'assets/product-images/Product-Pickachu.jpg',
            widht: 1024,
            height: 1024, 
            alt: 'A wooden plectrum with a hollow near the top. On the plectrum is an illustration of a yellow cartoon character with red cheeks and black ear tips, surrounded by the text "Pikachu" and other minor markings.', 
        },
    },
    {
        id: 2,
        name: 'Plectrickery',
        amount: 0, 
        price: 38, 
        rating: 2, 
        category: 'metall 🔩',    
        img: {
            url: 'assets/product-images/Product-Plectrickery.png',
            widht: 1024,
            height: 1024, 
            alt: 'A metallic guitar plectrum with the text "Plectrickery" engraved at the top, surrounded by geometric patterns and lines for a sleek and modern look.',
        },
    },
    {
        id: 3,
        name: 'Shred Zeppelin',
        amount: 0, 
        price: 42, 
        rating: 3, 
        category: 'metall 🔩',    
        img: {
            url: 'assets/product-images/Product-ShredZeppelin.jpg',
            widht: 1024,
            height: 1024, 
            alt: 'A close-up of a plectrum with a unique design. The base of the plectrum is in silver metal, and its center is filled with an intricate texture of intertwined golden threads',
        },
    },
    {
        id: 4,
        name: 'Sir Strums-a-Lot',
        amount: 0, 
        price: 26, 
        rating: 2, 
        category: 'trä 🪵',    
        img: {
            url: 'assets/product-images/Product-SirStrumsALot.jpg',
            widht: 1024,
            height: 1024,
            alt: 'A light wood plectrum with a detailed engraving on the front. The engraving shows an illustration of a man wearing a tall hat surrounded by decorative lines. The text above and below the illustration reads: “SIR STRUMS-A-LOT',  
        },
    },
    {
        id: 5,
        name: 'Pickle Ricktum',
        amount: 0, 
        price: 35, 
        rating: 5, 
        category: 'trä 🪵',    
        img: {
            url: 'assets/product-images/Product-PickleRicktum.jpg',
            widht: 1024,
            height: 1024,
            alt: 'A wooden plectrum with a cartoon design depicting a green face with a surprised expression, inspired by a pickle. The text "Pickle" is written at the top in a playful style. The plectrum has a light wood finish with a small hole in the bottom', 
        },
    },
    {
        id: 6,
        name: 'Strumb & Dumb',
        amount: 0, 
        price: 18, 
        rating: 4, 
        category: 'plast 🧴',    
        img: {
            url: 'assets/product-images/Product-StrumbAndDumb.jpg',
            widht: 1024,
            height: 1024, 
            alt: 'An orange plectrum with a black and white illustration of a person playing a mandolin. The plectrum has the text "STRUM" in large letters and slogans as well as decorative texts around the edge.',
        },
    },
    {
        id: 7,
        name: 'Pickasso',
        amount: 0, 
        price: 26, 
        rating: 2, 
        category: 'trä 🪵',    
        img: {
            url: 'assets/product-images/Product-Pickasso.jpg',
            widht: 1024,
            height: 1024, 
            alt: 'A wooden plectrum with a unique, colorful geometric design in red, blue, yellow and green. The design is reminiscent of a stylized face mask with symmetrical patterns and takes inspiration from the great artist Pablo Picasso works.',
        },
    },
    {
        id: 8,
        name: 'Pluck Norris',
        amount: 0, 
        price: 20, 
        rating: 5, 
        category: 'plast 🧴',    
        img: {
            url: 'assets/product-images/Product-PluckNorris.jpg',
            widht: 1024,
            height: 1024, 
            alt: 'A white plectrum with a detailed black and white illustration of a man with a cowboy hat and beard, which makes a powerful and iconic impression. The inspiration is based on the well-known profile Chuck Norris.',
        },
    },
    {
        id: 9,
        name: 'Strumdog Millionaire',
        amount: 0, 
        price: 34, 
        rating: 1, 
        category: 'metall 🔩',    
        img: {
            url: 'assets/product-images/Product-StrumdogMillionaire.jpg',
            widht: 1024,
            height: 1024, 
            alt: 'A blue plectrum with a raised, detailed gold decoration that includes an ornate frame and the text "STRUMDOG MILLIONAIRE". The plectrum has a luxurious and elegant design that gives the impression of exclusivity',
        },
    }
];

export default products;