const products = [
    {
        id: 0,
        name: 'Plucky McStrumface',
        amount: 0, 
        price: 16, 
        rating: 3, 
        category: 'plast',
        img: {
            url: 'assets/product-images/Product-PluckyMcStrumface.png',
            widht: 1024,
            height: 1024, 
        },
    },
    {
        id: 1,
        name: 'Pickachu',
        amount: 0, 
        price: 35, 
        rating: 5, 
        category: 'trä',
        img: {
            url: 'assets/product-images/Product-Pickachu.jpg',
            widht: 1024,
            height: 1024, 
        },
    },
    {
        id: 2,
        name: 'Plectrickery',
        amount: 0, 
        price: 38, 
        rating: 2, 
        category: 'metall',
        img: {
            url: 'assets/product-images/Product-Plectrickery.png',
            widht: 1024,
            height: 1024, 
        },
    },
    {
        id: 3,
        name: 'Shred Zeppelin',
        amount: 0, 
        price: 42, 
        rating: 3, 
        category: 'metall',
        img: {
            url: 'assets/product-images/Product-ShredZeppelin.jpg',
            widht: 1024,
            height: 1024, 
        },
    },
    {
        id: 4,
        name: 'Sir Strums-a-Lot',
        amount: 0, 
        price: 26, 
        rating: 2, 
        category: 'trä',
        img: {
            url: 'assets/product-images/Product-SirStrumsALot.jpg',
            widht: 1024,
            height: 1024, 
        },
    },
    {
        id: 5,
        name: 'Pickle Ricktum',
        amount: 0, 
        price: 35, 
        rating: 5, 
        category: 'trä',
        img: {
            url: 'assets/product-images/Product-PickleRicktum.jpg',
            widht: 1024,
            height: 1024, 
        },
    },
    {
        id: 6,
        name: 'Strumb & Dumb',
        amount: 0, 
        price: 18, 
        rating: 4, 
        category: 'plast',
        img: {
            url: 'assets/product-images/Product-StrumbAndDumb.jpg',
            widht: 1024,
            height: 1024, 
        },
    },
    {
        id: 7,
        name: 'Pickasso',
        amount: 0, 
        price: 26, 
        rating: 2, 
        category: 'trä',
        img: {
            url: 'assets/product-images/Product-Pickasso.jpg',
            widht: 1024,
            height: 1024, 
        },
    },
    {
        id: 8,
        name: 'Pluck Norris',
        amount: 0, 
        price: 20, 
        rating: 5, 
        category: 'plast',
        img: {
            url: 'assets/product-images/Product-PluckNorris.jpg',
            widht: 1024,
            height: 1024, 
        },
    },
    {
        id: 9,
        name: 'Strumdog Millionaire',
        amount: 0, 
        price: 34, 
        rating: 1, 
        category: 'metall',
        img: {
            url: 'assets/product-images/Product-StrumdogMillionaire.jpg',
            widht: 1024,
            height: 1024, 
        },
    }
];

export default products;